(self.AMP=self.AMP||[]).push({n:"amp-script",v:"2003261442330",f:(function(AMP,_){
var q;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function da(a){for(var b=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var r=da(this);
function u(){u=function(){};r.Symbol||(r.Symbol=ea)}function fa(a,b){this.W=a;ca(this,"description",{configurable:!0,writable:!0,value:b})}fa.prototype.toString=function(){return this.W};var ea=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new fa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function ha(){u();var a=r.Symbol.iterator;a||(a=r.Symbol.iterator=r.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ia(aa(this))}});ha=function(){}}function ia(a){ha();var b={next:a};b[r.Symbol.iterator]=function(){return this};return b}function ja(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}
function pa(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var qa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ra;if("function"==typeof Object.setPrototypeOf)ra=Object.setPrototypeOf;else{var sa;a:{var ta={a:!0},ua={};try{ua.__proto__=ta;sa=ua.a;break a}catch(a){}sa=!1}ra=sa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var va=ra,wa=/log|development/i.test(location.hash);
function xa(a,b,c,d,e){var f=e.executorsAllowed.includes(8);return{execute:function(a,d,e){if(f&&e){var g=a[d+1],k=b.getNode(g);if(k){var h=k.transferControlToOffscreen(),n={};c.messageToWorker((n[12]=9,n[13]=[k._index_],n[38]=h,n),[h])}else console.error("'OFFSCREEN_CANVAS_INSTANCE': getNode("+g+") is null.")}return d+2},print:function(a,b,c){return{type:"OFFSCREEN_CANVAS_INSTANCE",target:c,allowedExecution:f}}}}
var ya=[0,1,2,3,4,5,6,7,8,9,10,11,12],za={0:"ATTRIBUTES",1:"CHARACTER_DATA",2:"CHILD_LIST",3:"PROPERTIES",4:"EVENT_SUBSCRIPTION",5:"GET_BOUNDING_CLIENT_RECT",6:"LONG_TASK_START",7:"LONG_TASK_END",8:"OFFSCREEN_CANVAS_INSTANCE",9:"OBJECT_MUTATION",10:"OBJECT_CREATION",11:"IMAGE_BITMAP_INSTANCE",12:"STORAGE"};function Aa(a,b){Array.prototype.forEach.call(a,b)}
function Ba(a,b){var c=this;this.createNodes=function(a,b){var d=new Uint16Array(a),e=d.length;for(a=0;a<e;a+=5){if(3===d[a+1])var g=document.createTextNode(c.stringContext.get(d[a+3]));else if(8===d[a+1])g=document.createComment(c.stringContext.get(d[a+3]));else if(11===d[a+1])g=document.createDocumentFragment();else{var k=c.stringContext.get(d[a+2]);g=0!==d[a+4]?document.createElementNS(c.stringContext.get(d[a+4]),k):document.createElement(k);if(b&&!b.sanitize(g))continue}c.storeNode(g,d[a])}};
this.getNode=function(a){return(a=c.nodes.get(a))&&"BODY"===a.nodeName?c.baseElement:a};this.storeNodes=function(a){c.storeNode(a,++c.count);Aa(a.childNodes,function(a){return c.storeNodes(a)})};this.count=2;this.stringContext=a;this.nodes=new Map([[1,b],[2,b]]);this.baseElement=b;b._index_=2;Aa(b.childNodes,function(a){return c.storeNodes(a)})}Ba.prototype.storeNode=function(a,b){a._index_=b;this.nodes.set(b,a)};var Ca=new Map;function Da(a){return a&&"value"in a}
function Ea(a,b){Da(b)&&null===b.oninput&&(b.oninput=function(){return Fa(a,b)})}function Ga(a,b){Da(b)&&!Ca.get(b)&&((new MutationObserver(function(b){return b.map(function(b){return Fa(a,b.target)})})).observe(b,{attributes:!0}),Ca.set(b,!0))}function Fa(a,b){var c={},d={};return a.messageToWorker((d[12]=4,d[40]=(c[7]=b._index_,c[21]=b.value,c),d))}
function Ha(a){return Object.values(a).map(function(a){return[a.identifier,a.screenX,a.screenY,a.clientX,a.clientY,a.pageX,a.pageY,a.target._index_]})}
function Ia(a,b,c,d,e){function f(d,e,f,k){var n=a.get(f[k]),m=f[k+1];if(d===b.baseElement)e?addEventListener(n,g[m]=h(1,!!f[k+5])):removeEventListener(n,g[m]);else{var l=null!==d.oninput,p="change"===n;if(e){p&&(l=!0,d.onchange=null);var D=!!f[k+5];d.addEventListener(n,g[m]=h(d._index_,D))}else p&&(l=!1),d.removeEventListener(n,g[m]);Da(d)&&(l||Ea(c,d),Ga(c,d))}}function h(a,b){return function(d){b&&d.preventDefault();if(Da(d.currentTarget))Fa(c,d.currentTarget);else if("resize"===d.type){var e=
window,g=e.innerWidth,f=e.innerHeight;if(l[0]===g&&l[1]===f)return;e=l=[window.innerWidth,window.innerHeight];var k={};c.messageToWorker((k[12]=5,k[40]=e,k))}e={};k={};c.messageToWorker((k[12]=1,k[39]=(e[7]=a,e[25]=d.bubbles,e[26]=d.cancelable,e[27]=d.cancelBubble,e[28]=[d.currentTarget._index_||0],e[29]=d.defaultPrevented,e[30]=d.eventPhase,e[31]=d.isTrusted,e[32]=d.returnValue,e[13]=[d.target._index_||0],e[33]=d.timeStamp,e[12]=d.type,e[35]="keyCode"in d?d.keyCode:void 0,e[60]="pageX"in d?d.pageX:
void 0,e[61]="pageY"in d?d.pageY:void 0,e[65]="offsetX"in d?d.offsetX:void 0,e[66]="offsetY"in d?d.offsetY:void 0,e[62]="touches"in d?Ha(d.touches):void 0,e[63]="changedTouches"in d?Ha(d.changedTouches):void 0,e),k))}}var g=[],k=e.executorsAllowed.includes(4),l=[window.innerWidth,window.innerHeight];return{execute:function(a,c,d){var e=a[c+3],g=a[c+2],h=c+4+2*g,l=c+4+6*e+2*g;if(k&&d){var m=a[c+1];if(d=b.getNode(m))for(c+=4;c<l;){var p=c<=h;f(d,p,a,c);c+=p?2:6}else console.error("getNode("+m+") is null.")}return l},
print:function(c,d){var e=c[d+2],g=d+4+2*e;e=d+4+6*c[d+3]+2*e;var f=b.getNode(c[d+1]),h=[],l=[];for(d+=4;d<e;){var m=d<=g,p=m?l:h;p.push({type:a.get(c[d]),index:c[d+1]});d+=m?2:6}return{target:f,allowedExecution:k,removedEventListeners:h,addedEventListeners:l}}}}
function Ja(a,b,c,d,e){var f=e.executorsAllowed.includes(5);return{execute:function(a,d,e){if(f&&e)if(e=a[d+1],a=b.getNode(e)){var g=a.getBoundingClientRect();e={};c.messageToWorker((e[12]=6,e[13]=[a._index_],e[38]=[g.top,g.right,g.bottom,g.left,g.width,g.height],e))}else console.error("GET_BOUNDING_CLIENT_RECT: getNode("+e+") is null.");return d+2},print:function(a,c){return{type:"GET_BOUNDING_CLIENT_RECT",target:b.getNode(a[c+1]),allowedExecution:f}}}}
function Ka(a,b,c,d,e){var f=b.getNode,h=e.executorsAllowed.includes(2);return{execute:function(a,b,d){var e=a[b+4],g=a[b+5];if(h&&d){d=a[b+1];var k=f(d);k?(0<g&&a.slice(b+6+e,b+6+e+g).forEach(function(a){var b=f(a);b?b.remove():console.error("CHILD_LIST: getNode("+a+") is null.")}),0<e&&a.slice(b+6,b+6+e).forEach(function(d){var e=a[b+2],g=f(d);g&&(k.insertBefore(g,e&&f(e)||null),Ea(c,g),Ga(c,g))})):console.error("CHILD_LIST: getNode("+d+") is null.")}return b+6+e+g},print:function(a,b){var c=f(a[b+
1]),d=a[b+4],e=Array.from(a.slice(b+6+d,b+6+d+a[b+5])).map(function(a){return f(a)||a}),g=Array.from(a.slice(b+6,b+6+d)).map(function(a){return f(a)||a});return{target:c,allowedExecution:h,nextSibling:f(a[b+2])||null,previousSibling:f(a[b+3])||null,addedNodes:g,removedNodes:e}}}}
function La(a,b,c,d,e){function f(b,c){b=b[c+4];return 0!==b?a.get(b-1):null}var h=e.executorsAllowed.includes(0);return{execute:function(c,d,l){if(h&&l){l=c[d+1];var g=b.getNode(l),k=a.get(c[d+2]);c=f(c,d);g?null!=k&&(e.sanitizer?e.sanitizer.setAttribute(g,k,c):null==c?g.removeAttribute(k):g.setAttribute(k,c)):console.error("ATTR_LIST: getNode("+l+") is null.")}return d+5},print:function(c,d){var e=b.getNode(c[d+1]),g=a.get(c[d+2]);c=f(c,d);return{target:e,allowedExecution:h,attributeName:g,value:c,
remove:null==c}}}}function Ma(a,b,c,d,e){var f=e.executorsAllowed.includes(1);return{execute:function(c,d,e){if(f&&e){e=c[d+1];var g=b.getNode(e);c=c[d+2];g?c&&(g.textContent=a.get(c)):console.error("CHAR_DATA: getNode("+e+") is null.")}return d+3},print:function(c,d){return{target:b.getNode(c[d+1]),allowedExecution:f,value:a.get(c[d+2])}}}}
function Na(a,b,c,d,e){function f(b,c){var d=b[c+4];return 1===b[c+3]?1===d:0!==d?a.get(d):null}var h=e.executorsAllowed.includes(3);return{execute:function(c,d,l){if(h&&l){l=c[d+1];var g=b.getNode(l),k=a.get(c[d+2]);c=f(c,d);g?k&&null!=c&&(e.sanitizer?e.sanitizer.setProperty(g,k,String(c)):g[k]=c):console.error("PROPERTY: getNode("+l+") is null.")}return d+5},print:function(c,d){var e=b.getNode(c[d+1]),g=a.get(c[d+2]);c=f(c,d);return{target:e,name:g,value:c,allowedExecution:h}}}}
function Oa(a,b,c,d,e){var f=e.executorsAllowed.includes(6),h=0,g;return{execute:function(a,b,c){f&&c&&e.longTask&&(6===a[b]?(h++,g||e.longTask(new Promise(function(a){return g=a}))):7===a[b]&&(h--,g&&0>=h&&(g(),g=null,h=0)));return b+2},print:function(a,b){return{type:za[a[b]],allowedExecution:f}},get active(){return null!==g}}}var $a=new Float32Array(1),ab=new Uint16Array($a.buffer);
function w(a,b,c,d,e,f){for(var h=[],g=0;g<c;g++)switch(a[b++]){case 1:h.push(a[b++]);break;case 2:ab[0]=a[b++];ab[1]=a[b++];h.push($a[0]);break;case 3:h.push(d.get(a[b++]));break;case 4:var k=a[b++],l=w(a,b,k,d,e,f);h.push(l.args);b=l.offset;break;case 5:if(!f)throw Error("objectContext not provided.");h.push(f.get(a[b++]));break;case 6:var p=e.getNode(a[b++]);h.push(p.getContext("2d"));break;case 7:h.push(e.getNode(a[b++]));break;default:throw Error("Cannot deserialize argument.");}return{args:h,
offset:b}}function bb(a,b,c,d,e){var f=e.executorsAllowed.includes(9);return{execute:function(c,e,k){var g=a.get(c[e+1]),h=c[e+2];e=w(c,e+3,1,a,b,d);var m=e.offset,n=e.args;e=n[0];c=w(c,m,h,a,b,d);var D=c.offset;c=c.args;f&&k&&(cb(e,g)?e[g]=c[0]:e[g].apply(e,c instanceof Array?c:pa(ja(c))));return D},print:function(c,e){var g=a.get(c[e+1]);c=w(c,e+3,1,a,b,d).args[0];return{type:"OBJECT_MUTATION",target:c,functionName:g,isSetter:cb(c,g),allowedExecution:f}}}}
function cb(a,b){if(!a)throw Error("Property "+b+" does not exist on "+a+".");var c=Object.getOwnPropertyDescriptor(a,b);return void 0!==c?"set"in c:cb(Object.getPrototypeOf(a),b)}
function db(a,b,c,d,e){var f=e.executorsAllowed.includes(10);if(!d)throw Error("objectContext is not defined.");return{execute:function(c,e,k){var g=a.get(c[e+1]),h=c[e+2],m=c[e+3],n=w(c,e+4,1,a,b,d);e=n.args[0];m=w(c,n.offset,m,a,b,d);c=m.offset;m=m.args;f&&k&&"new"!==g&&d.store(h,e[g].apply(e,m instanceof Array?m:pa(ja(m))));return c},print:function(c,e){var g=a.get(c[e+1]),h=c[e+2],p=c[e+3];return{type:"OBJECT_CREATION",target:w(c,e+4,1,a,b,d).args[0],functionName:g,objectId:h,argCount:p,allowedExecution:f}}}}
function eb(a,b,c,d,e){var f=e.executorsAllowed.includes(11);return{execute:function(a,d,e){if(f&&e){e=a[d+1];var g=b.getNode(e);g?self.createImageBitmap(g).then(function(b){var e={};c.messageToWorker((e[12]=10,e[73]=a[d+2],e[38]=b,e),[b])}):console.error("IMAGE_BITMAP_INSTANCE: getNode("+e+") is null.")}return d+3},print:function(a,c){return{type:"IMAGE_BITMAP_INSTANCE",target:b.getNode(a[c+1]),allowedExecution:f,callIndex:a[c+2]}}}}
function fb(a,b,c,d,e){function f(a,b,c){if(e.sanitizer)e.sanitizer.setStorage(a,b,c);else{if(0===a)var d=window.localStorage;else 1===a&&(d=window.sessionStorage);if(d)if(null==b)if(null==c)d.clear();else throw Error("Unexpected storage operation.");else null==c?d.removeItem(b):d.setItem(b,c);else console.error('STORAGE: Unexpected location: "'+a+'".')}}function h(a,b){e.sanitizer&&2===a?e.sanitizer.getStorage(a,b).then(function(d){var e={};d=(e[12]=11,e[74]=b||"",e[75]=a,e[21]=d,e);c.messageToWorker(d)}):
console.error("STORAGE: Sanitizer not found or unsupported location:",a)}var g=e.executorsAllowed.includes(12);return{execute:function(b,c,d){if(g&&d){var e=b[c+1];d=b[c+2];var k=b[c+3],l=b[c+4];b=0<k?a.get(k):null;var p=0<l?a.get(l):null;1===e?h(d,b):2===e&&f(d,b,p)}return c+5},print:function(b,c){var d=b[c+1],e=b[c+2],f=b[c+3];b=b[c+4];f=0<f?a.get(f):null;b=0<b?a.get(b):null;return{type:"STORAGE",operation:d,location:e,key:f,value:b,allowedExecution:g}}}}
function gb(a,b,c,d,e){var f=this;this.mutationQueue=[];this.pendingMutations=!1;this.syncFlush=function(a){void 0===a&&(a=!0);var b=[];f.mutationQueue.forEach(function(c){for(var d=0,e=c.length;d<e;){var g=c[d],h;if(!(h=a)){a:switch(g){case 4:case 5:case 6:case 7:case 12:case 8:h=!1;break a;default:h=!0}h=!h}var k=h;k||b.push(g);var l=f.executors[g];wa&&console.log(k?"":"[disallowed]",za[g],l.print(c,d));d=l.execute(c,d,k)}});f.mutationQueue=[];f.pendingMutations=!1;return b};this.stringContext=
a;this.nodeContext=b;this.sanitizer=d.sanitizer;this.mutationPumpFunction=d.mutationPump;a=[a,b,c,e,d];var h=Oa.apply(null,a);b={};this.executors=(b[2]=Ka.apply(null,a),b[0]=La.apply(null,a),b[1]=Ma.apply(null,a),b[3]=Na.apply(null,a),b[4]=Ia.apply(null,a),b[5]=Ja.apply(null,a),b[6]=h,b[7]=h,b[8]=xa.apply(null,a),b[9]=bb.apply(null,a),b[10]=db.apply(null,a),b[11]=eb.apply(null,a),b[12]=fb.apply(null,a),b)}
gb.prototype.mutate=function(a,b,c,d){this.stringContext.storeValues(c);this.nodeContext.createNodes(b,this.sanitizer);this.mutationQueue=this.mutationQueue.concat(d);this.pendingMutations||(this.pendingMutations=!0,this.mutationPumpFunction(this.syncFlush,a))};function hb(){this.strings=[]}hb.prototype.get=function(a){return this.strings[a]||""};hb.prototype.store=function(a){this.strings.push(a)};hb.prototype.storeValues=function(a){var b=this;a.forEach(function(a){return b.store(a)})};
function ib(a){return Object.assign({},{mutationPump:requestAnimationFrame.bind(null),executorsAllowed:ya},a)}var jb=[8,3];
function kb(a,b,c,d){var e=[].slice.call(a.childNodes).filter(c),f={},h=(f[7]=a._index_,f[11]=0,f[0]=a.nodeType,f[1]=b(a.localName||a.nodeName),f[4]=e.map(function(a){return kb(a,b,c,d)}),f[2]=[].map.call(a.attributes||[],function(a){return[b(a.namespaceURI||"null"),b(a.name),b(a.value)]}),f);null!=a.namespaceURI&&(h[6]=b(a.namespaceURI));jb.includes(a.nodeType)&&null!==a.textContent&&(h[5]=b(a.textContent));Ea(d,a);Ga(d,a);return h}
function lb(a,b,c){function d(a){if(f.has(a))return f.get(a);var b=e.length;f.set(a,b);e.push(a);return b}b=b.hydrateFilter||function(){return!0};var e=[],f=new Map,h=kb(a,d,b,c);return{skeleton:h,strings:e}}function mb(a,b,c){return kb(a,function(a){return a},b.hydrateFilter||function(){return!0},c)}function nb(a,b){return null!=b&&a.getNode(b[0])||b}
function ob(a){var b={nodeType:a[0],name:a[1],attributes:null,childNodes:null},c=a[2];c&&(b.attributes=c.map(function(a){return{name:a[1],value:a[2]}}));var d=a[4];d&&(b.childNodes=d.map(ob));return b}
function pb(a,b){function c(b){return"number"===typeof b||"boolean"===typeof b?void 0!==b?b:null:void 0!==b&&null!==b?nb(a,b):null}return{type:b[12],bubbles:c(b[25]),cancelable:c(b[26]),cancelBubble:c(b[27]),defaultPrevented:c(b[29]),eventPhase:c(b[30]),isTrusted:c(b[31]),returnValue:c(b[32]),currentTarget:c(b[28]),target:c(b[13]),scoped:c(b[34]),keyCode:c(b[35])}}
function tb(a,b){if(1==b[12])a={type:"EVENT",event:pb(a,b[39])};else if(4==b[12]){b=b[40];var c=b[7];a={type:"SYNC",sync:{target:a.getNode(c)||c,value:b[21]}}}else a=6===b[12]?{type:"GET_BOUNDING_CLIENT_RECT",target:nb(a,b[13])}:"Unrecognized MessageToWorker type: "+b[12];return a}
function ub(a,b,c,d,e){this.nodeContext=b;this.config=e;var f=lb(a,e,this);b=f.skeleton;f=f.strings;var h=[],g=[],k=e.sanitizer?e.sanitizer.getStorage(0):window.localStorage,l=e.sanitizer?e.sanitizer.getStorage(1):window.sessionStorage;for(m in a.style)h.push(m);for(var p in a)p.startsWith("on")&&g.push(p);var m="'use strict';(function(){"+c+"self['window']=self;var workerDOM=WorkerThread.workerDOM;WorkerThread.hydrate(workerDOM.document,"+JSON.stringify(f)+","+JSON.stringify(b)+","+JSON.stringify(h)+
","+JSON.stringify(g)+",["+window.innerWidth+","+window.innerHeight+"],"+JSON.stringify(k)+","+JSON.stringify(l)+");workerDOM.document[59](this);Object.keys(workerDOM).forEach(function(k){self[k]=workerDOM[k]});}).call(self);"+d+"//# sourceURL="+encodeURI(e.authorURL);this[55]=new Worker(URL.createObjectURL(new Blob([m])));wa&&console.info("debug","hydratedNode",ob(mb(a,e,this)));if(e.onCreateWorker)e.onCreateWorker(a,f,b,h)}
ub.prototype.messageToWorker=function(a,b){wa&&console.info("debug","messageToWorker",tb(this.nodeContext,a));if(this.config.onSendMessage)this.config.onSendMessage(a);this.worker.postMessage(a,b||[])};r.Object.defineProperties(ub.prototype,{worker:{configurable:!0,enumerable:!0,get:function(){return this[55]}}});function vb(){this.objects=new Map}vb.prototype.store=function(a,b){this.objects.set(a,b)};
vb.prototype.get=function(a){var b=this.objects.get(a);if(b)return b;throw Error("Object with id ("+a+") does not exist.");};var wb=[3,2];
function xb(a,b,c){var d=new hb,e=new vb,f=new Ba(d,b),h=ib(c);return a.then(function(a){a=ja(a);var g=a.next().value,l=a.next().value;if(g&&l&&c.authorURL){a=new ub(b,f,g,l,h);var p=new gb(d,f,a,h,e);a.worker.onmessage=function(a){var b=a.data;if(wb.includes(b[12])&&(p.mutate(b[54],b[37],b[41],new Uint16Array(b[36])),c.onReceiveMessage))c.onReceiveMessage(a)};return a.worker}return null})}
function yb(a){if(null!==a.parentNode){var b=(a.parentNode.localName||a.parentNode.nodeName).toLowerCase();return!/amp-/.test(b)||"amp-script"===b}return!0}function zb(a,b,c){c.hydrateFilter=yb;return xb(b,a,c)};function Ab(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var Bb=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function Cb(a){var b=Object.create(null);if(!a)return b;for(var c;c=Bb.exec(a);){var d=Ab(c[1],c[1]),e=c[2]?Ab(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var Db="";
function Eb(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=Cb(c.location.originalHash||c.location.hash),h=d.spt;d=d.esm;var g=Cb(c.location.search);Db||(Db=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"012003261442330");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||c.AMP_DEV_MODE),examiner:"2"==f.development,esm:d,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,
version:"2003261442330",rtvVersion:Db,singlePassType:h};c=b.__AMP_MODE=c}return c};var x=self.AMP_CONFIG||{},Fb={thirdParty:x.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:x.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof x.thirdPartyFrameRegex?new RegExp(x.thirdPartyFrameRegex):x.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:x.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:x.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:x.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:x.geoApiUrl};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var Gb=self.__AMP_LOG;function z(){if(!Gb.user)throw Error("failed to call initLogConstructor");return Gb.user}function A(){if(Gb.dev)return Gb.dev;throw Error("failed to call initLogConstructor");}function E(a,b,c,d,e,f){return z().assert(a,b,c,d,e,f,void 0,void 0,void 0,void 0,void 0)};var Hb=Object.prototype.hasOwnProperty;function Ib(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function F(a){return a||{}};function I(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function Jb(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};function Kb(a){var b=["\u26a14email","amp4email"],c=a.documentElement,d=b.some(function(a){return c.hasAttribute(a)});return d};function Lb(){var a=100;this.Y=a;this.H=this.L=0;this.A=Object.create(null)}Lb.prototype.has=function(a){return!!this.A[a]};Lb.prototype.get=function(a){var b=this.A[a];if(b)return b.access=++this.H,b.payload};Lb.prototype.put=function(a,b){this.has(a)||this.L++;this.A[a]={payload:b,access:this.H};if(!(this.L<=this.Y)){A().warn("lru-cache","Trimming LRU cache");a=this.A;var c=this.H+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.L--)}};var Mb=F({c:!0,v:!0,a:!0,ad:!0,action:!0}),Nb,Ob,Pb=/[?&]amp_js[^&]*/,Qb=/[?&]amp_gsa[^&]*/,Rb=/[?&]amp_r[^&]*/,Sb=/[?&]amp_kit[^&]*/,Tb=/[?&]usqp[^&]*/;
function J(a){var b;Nb||(Nb=self.document.createElement("a"),Ob=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new Lb));var c=b?null:Ob,d=Nb;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=
e.hostname;e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function Ub(a){"string"==typeof a&&(a=J(a));return Fb.cdnProxyRegex.test(a.origin)}
function Vb(a){"string"==typeof a&&(a=J(a));if(!Ub(a))return a.href;var b=a.pathname.split("/");E(Mb[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);E(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Pb,"").replace(Qb,"").replace(Rb,"").replace(Sb,"").replace(Tb,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function gc(a,b){"string"==typeof b&&(b=J(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=J(d));c=c.replace(/\\/g,"/");var e=J(c);c=I(c.toLowerCase(),e.protocol)?e.href:I(c,"//")?d.protocol+c:I(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function hc(a){var b=J(a),c=Cb(b.search);E(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};var ic=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function jc(a){for(var b=[],c;c=ic.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var h=c[3].toLowerCase();if("w"==h)e=parseInt(c[2],10);else if("x"==h)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new kc(b)}
function kc(a){E(0<a.length,"Srcset must have at least one source");this.h=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}E(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?lc:mc);this.U=b}
kc.prototype.select=function(a,b){if(this.U){b*=a;a=this.h;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var h=a[f].width,g=Math.abs(h-b);if(g<=1.1*d||1.2<b/e)c=f,d=g,e=h;else break}b=c}else{a=this.h;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.h[b].url};kc.prototype.getUrls=function(){return this.h.map(function(a){return a.url})};
kc.prototype.stringify=function(a){for(var b=[],c=this.h,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.U?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function lc(a,b){E(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function mc(a,b){E(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};function nc(a,b,c){return oc(b)?pc(a,b,c):c}function oc(a){return"src"==a||"href"==a||"xlink:href"==a||"srcset"==a}function pc(a,b,c){var d=self.location;hc(c);var e=Ub(d),f=J(Vb(d));if("href"==b&&!I(c,"#"))return gc(c,f);if("src"==b)return"amp-img"==a?qc(c,f,e):gc(c,f);if("srcset"==b){try{var h=jc(c)}catch(g){return z().error("URL-REWRITE","Failed to parse srcset: ",g),c}return h.stringify(function(a){return qc(a,f,e)})}return c}
function qc(a,b,c){a=J(gc(a,b));return"data:"==a.protocol||Ub(a)||!c?a.href:Fb.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var rc={"AMP-IMG":["src","srcset","layout","width","height"]};function sc(a,b){var c=I(a.tagName,"AMP-"),d=a.hasAttribute("i-amphtml-binding");if(!d&&rc[a.tagName])a.setAttribute("i-amphtml-ignore","");else if(d||c)a.hasAttribute("i-amphtml-key")||a.setAttribute("i-amphtml-key",b())}
var tc={applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,style:!0,video:!0},uc={"amp-accordion":!0,"amp-anim":!0,"amp-bind-macro":!0,"amp-carousel":!0,"amp-fit-text":!0,"amp-img":!0,"amp-layout":!0,"amp-selector":!0,"amp-sidebar":!0,"amp-timeago":!0},vc="a b br caption col colgroup code del div em hr i ins li mark ol p q s small span strong sub sup table tbody time td th thead tfoot tr u ul".split(" "),wc="amp-fx fallback heights layout min-font-size max-font-size on option placeholder submitting submit-success submit-error validation-for verify-error visible-when-invalid href style text subscriptions-action subscriptions-actions subscriptions-decorate subscriptions-dialog subscriptions-display subscriptions-section subscriptions-service amp-nested-submenu amp-nested-submenu-open amp-nested-submenu-close itemprop".split(" "),
xc={a:["rel","target"],div:["template"],form:["action-xhr","verify-xhr","custom-validation-reporting","target"],input:["mask-output"],template:["type"],textarea:["autoexpand"]},yc=["_top","_blank"],zc=/^(?:\w+script|data|blob):/i,Ac=/^(?:blob):/i,Bc=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g,Cc=Object.freeze(F({input:{type:/(?:image|button)/i}})),Dc=Object.freeze(F({input:{type:/(?:button|file|image|password)/i}})),Ec=Object.freeze("form formaction formmethod formtarget formnovalidate formenctype".split(" ")),
Fc=Object.freeze(F({input:Ec,textarea:Ec,select:Ec})),Gc=Object.freeze(F({"amp-anim":["controls"],form:["name"]})),Hc=/!important|position\s*:\s*fixed|position\s*:\s*sticky/i;
function Ic(a,b,c,d){var e=!0;e=void 0===e?!1:e;var f=c?c.replace(Bc,""):"";if(!e){if(I(b,"on")&&"on"!=b)return!1;var h=f.toLowerCase();if(0<=h.indexOf("<script")||0<=h.indexOf("\x3c/script")||zc.test(f))return!1}if(Ac.test(f))return!1;if("style"==b)return!Hc.test(c);if("class"==b&&c&&/(^|\W)i-amphtml-/i.test(c)||oc(b)&&/__amp_source_origin/.test(c))return!1;var g=Kb(d),k=Object.assign(Ib(),Fc,g?Gc:{})[a];if(k&&-1!=k.indexOf(b))return!1;var l=Object.assign(Ib(),Cc,g?Dc:{})[a];if(l){var p=l[b];if(p&&
-1!=c.search(p))return!1}return!0};function Jc(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Kc(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Lc(a,b){Kc(a.documentElement,function(){return!!a.body},b)}function Mc(a){return new Promise(function(b){return Lc(a,b)})};var K=Object.freeze||function(a){return a},Nc=K("a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" ")),
Oc=K("svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform audio canvas circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan video view vkern".split(" ")),Pc=K("feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" ")),
Qc=K("math menclose merror mfenced mfrac mglyph mi mlabeledtr mmultiscripts mn mo mover mpadded mphantom mroot mrow ms mspace msqrt mstyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" ")),Rc=K(["#text"]),Sc=Object.freeze||function(a){return a},Tc=Sc("accept action align alt autocomplete background bgcolor border cellpadding cellspacing checked cite class clear color cols colspan controls coords crossorigin datetime default dir disabled download enctype face for headers height hidden high href hreflang id integrity ismap label lang list loop low max maxlength media method min minlength multiple name noshade novalidate nowrap open optimum pattern placeholder poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title type usemap valign value width xmlns".split(" ")),
Uc=Sc("accent-height accumulate additive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter filterunits flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio primitiveunits r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility version vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" ")),
Vc=Sc("accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle encoding fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" ")),
Wc=Sc(["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"]),Xc=Object.hasOwnProperty,Yc=Object.setPrototypeOf,Zc=("undefined"!==typeof Reflect&&Reflect).apply;Zc||(Zc=function(a,b,c){return a.apply(b,c)});function L(a,b){Yc&&Yc(a,null);for(var c=b.length;c--;){var d=b[c];if("string"===typeof d){var e=d.toLowerCase();e!==d&&(Object.isFrozen(b)||(b[c]=e),d=e)}a[d]=!0}return a}function $c(a){var b={},c=void 0;for(c in a)Zc(Xc,a,[c])&&(b[c]=a[c]);return b}
var M=Object.seal||function(a){return a},ad=M(/\{\{[\s\S]*|[\s\S]*\}\}/gm),bd=M(/<%[\s\S]*|[\s\S]*%>/gm),cd=M(/^data-[\-\w.\u00B7-\uFFFF]/),dd=M(/^aria-[\-\w]+$/),ed=M(/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i),fd=M(/^(?:\w+script|data):/i),gd=M(/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g);u();u();ha();
var N="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){u();u();u();return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};function R(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}var hd=("undefined"!==typeof Reflect&&Reflect).apply,id=Array.prototype.slice,jd=Object.freeze;hd||(hd=function(a,b,c){return a.apply(b,c)});
function kd(a,b){if("object"!==("undefined"===typeof a?"undefined":N(a))||"function"!==typeof a.createPolicy)return null;var c=null,d="data-tt-policy-suffix";b.currentScript&&b.currentScript.hasAttribute(d)&&(c=b.currentScript.getAttribute(d));var e="dompurify"+(c?"#"+c:"");try{return a.createPolicy(e,{createHTML:function(a){return a}})}catch(f){return console.warn("TrustedTypes policy "+e+" could not be created."),null}}
function ld(){function a(a){var c,e=void 0,f;d("beforeSanitizeAttributes",a,null);var g=a.attributes;if(g){var G={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:v};for(f=g.length;f--;){var h=c=g[f],n=h.name,l=h.namespaceURI;c=c.value.trim();var p=n.toLowerCase();G.attrName=p;G.attrValue=c;G.keepAttr=!0;d("uponSanitizeAttribute",a,G);c=G.attrValue;if("name"===p&&"IMG"===a.nodeName&&g.id)e=g.id,g=hd(id,g,[]),k("id",a),k(n,a),g.indexOf(e)>f&&a.setAttribute("id",e.value);else if("INPUT"!==a.nodeName||
"type"!==p||"file"!==c||!G.keepAttr||!v[p]&&Pa[p])"id"===n&&a.setAttribute(n,""),k(n,a);else continue;if(G.keepAttr)if(/svg|math/i.test(a.namespaceURI)&&(new RegExp("</("+Object.keys(Xb).join("|")+")","i")).test(c))k(n,a);else{O&&(c=c.replace(ad," "),c=c.replace(bd," "));var D=a.nodeName.toLowerCase();if(b(D,p,c))try{l?a.setAttributeNS(l,n,c):a.setAttribute(n,c),m.removed.pop()}catch(oe){}}}d("afterSanitizeAttributes",a,null)}}function b(a,b,c){if(Yb&&("id"===b||"name"===b)&&(c in y||c in Md))return!1;
if(!Qa||!cd.test(b))if(!Zb||!dd.test(b))if(!v[b]||Pa[b]||!(Ra[b]||Sa.test(c.replace(gd,""))||("src"===b||"xlink:href"===b||"href"===b)&&"script"!==a&&0===c.indexOf("data:")&&Nd[a]||$b&&!fd.test(c.replace(gd,"")))&&c)return!1;return!0}function c(a){d("beforeSanitizeElements",a,null);if(f(a))return l(a),!0;var b=a.nodeName.toLowerCase();d("uponSanitizeElement",a,{tagName:b,allowedTags:t});if(("svg"===b||"math"===b)&&0!==a.querySelectorAll("p, br").length)return l(a),!0;if(!t[b]||ka[b]){if(Ta&&!Xb[b]&&
"function"===typeof a.insertAdjacentHTML)try{var c=a.innerHTML;a.insertAdjacentHTML("AfterEnd",B?B.createHTML(c):c)}catch(me){}l(a);return!0}if("noscript"===b&&/<\/noscript/i.test(a.innerHTML)||"noembed"===b&&/<\/noembed/i.test(a.innerHTML))return l(a),!0;!ac||a.firstElementChild||a.content&&a.content.firstElementChild||!/</g.test(a.textContent)||(m.removed.push({element:a.cloneNode()}),a.innerHTML=a.innerHTML?a.innerHTML.replace(/</g,"&lt;"):a.textContent.replace(/</g,"&lt;"));O&&3===a.nodeType&&
(b=a.textContent,b=b.replace(ad," "),b=b.replace(bd," "),a.textContent!==b&&(m.removed.push({element:a.cloneNode()}),a.textContent=b));d("afterSanitizeElements",a,null);return!1}function d(a,b,c){C[a]&&C[a].forEach(function(a){a.call(m,b,c,P)})}function e(a){return"object"===("undefined"===typeof ba?"undefined":N(ba))?a instanceof ba:a&&"object"===("undefined"===typeof a?"undefined":N(a))&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName}function f(a){return a instanceof Od||a instanceof
Pd?!1:"string"===typeof a.nodeName&&"string"===typeof a.textContent&&"function"===typeof a.removeChild&&a.attributes instanceof Qd&&"function"===typeof a.removeAttribute&&"function"===typeof a.setAttribute&&"string"===typeof a.namespaceURI?!1:!0}function h(a){return Rd.call(a.ownerDocument||a,a,la.SHOW_ELEMENT|la.SHOW_COMMENT|la.SHOW_TEXT,function(){return la.FILTER_ACCEPT},!1)}function g(a){var b=void 0,c=void 0;if(Ua)a="<remove></remove>"+a;else{var d=a.match(/^[\s]+/);(c=d&&d[0])&&(a=a.slice(c.length))}if(qb)try{b=
(new Sd).parseFromString(a,"text/html")}catch(ne){}rb&&L(ka,["title"]);if(!b||!b.documentElement){var e=b=Va.createHTMLDocument("");d=e.body;d.parentNode.removeChild(d.parentNode.firstElementChild);d.outerHTML=B?B.createHTML(a):a}a&&c&&b.body.insertBefore(y.createTextNode(c),b.body.childNodes[0]||null);return Td.call(b,V?"html":"body")[0]}function k(a,b){try{m.removed.push({attribute:b.getAttributeNode(a),from:b})}catch(Wb){m.removed.push({attribute:null,from:b})}b.removeAttribute(a)}function l(a){m.removed.push({element:a});
try{a.parentNode.removeChild(a)}catch(H){a.outerHTML=bc}}function p(a){P&&P===a||(a&&"object"===("undefined"===typeof a?"undefined":N(a))||(a={}),t="ALLOWED_TAGS"in a?L({},a.ALLOWED_TAGS):cc,v="ALLOWED_ATTR"in a?L({},a.ALLOWED_ATTR):dc,Ra="ADD_URI_SAFE_ATTR"in a?L($c(ec),a.ADD_URI_SAFE_ATTR):ec,ka="FORBID_TAGS"in a?L({},a.FORBID_TAGS):{},Pa="FORBID_ATTR"in a?L({},a.FORBID_ATTR):{},Q="USE_PROFILES"in a?a.USE_PROFILES:!1,Zb=!1!==a.ALLOW_ARIA_ATTR,Qa=!1!==a.ALLOW_DATA_ATTR,$b=a.ALLOW_UNKNOWN_PROTOCOLS||
!1,ac=a.SAFE_FOR_JQUERY||!1,O=a.SAFE_FOR_TEMPLATES||!1,V=a.WHOLE_DOCUMENT||!1,W=a.RETURN_DOM||!1,Wa=a.RETURN_DOM_FRAGMENT||!1,fc=a.RETURN_DOM_IMPORT||!1,Xa=a.RETURN_TRUSTED_TYPE||!1,Ua=a.FORCE_BODY||!1,Yb=!1!==a.SANITIZE_DOM,Ta=!1!==a.KEEP_CONTENT,ma=a.IN_PLACE||!1,Sa=a.ALLOWED_URI_REGEXP||Sa,O&&(Qa=!1),Wa&&(W=!0),Q&&(t=L({},[].concat(R(Rc))),v=[],!0===Q.html&&(L(t,Nc),L(v,Tc)),!0===Q.svg&&(L(t,Oc),L(v,Uc),L(v,Wc)),!0===Q.svgFilters&&(L(t,Pc),L(v,Uc),L(v,Wc)),!0===Q.mathMl&&(L(t,Qc),L(v,Vc),L(v,Wc))),
a.ADD_TAGS&&(t===cc&&(t=$c(t)),L(t,a.ADD_TAGS)),a.ADD_ATTR&&(v===dc&&(v=$c(v)),L(v,a.ADD_ATTR)),a.ADD_URI_SAFE_ATTR&&L(Ra,a.ADD_URI_SAFE_ATTR),Ta&&(t["#text"]=!0),V&&L(t,["html","head","body"]),t.table&&(L(t,["tbody"]),delete ka.tbody),jd&&jd(a),P=a)}function m(a){return ld(a)}var n=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;m.version="2.0.7";m.removed=[];if(!n||!n.document||9!==n.document.nodeType)return m.isSupported=!1,m;var D=n.document,qb=!1,
rb=!1,y=n.document,sb=n.DocumentFragment,ba=n.Node,la=n.NodeFilter,na=n.NamedNodeMap,Qd=void 0===na?n.NamedNodeMap||n.MozNamedAttrMap:na,Od=n.Text,Pd=n.Comment,Sd=n.DOMParser;na=n.TrustedTypes;if("function"===typeof n.HTMLTemplateElement){var Ya=y.createElement("template");Ya.content&&Ya.content.ownerDocument&&(y=Ya.content.ownerDocument)}var B=kd(na,D),bc=B?B.createHTML(""):"",oa=y,Va=oa.implementation,Rd=oa.createNodeIterator,Td=oa.getElementsByTagName,Ud=oa.createDocumentFragment,Vd=D.importNode,
C={};m.isSupported=Va&&"undefined"!==typeof Va.createHTMLDocument&&9!==y.documentMode;var Sa=ed,t=null,cc=L({},[].concat(R(Nc),R(Oc),R(Pc),R(Qc),R(Rc))),v=null,dc=L({},[].concat(R(Tc),R(Uc),R(Vc),R(Wc))),ka=null,Pa=null,Zb=!0,Qa=!0,$b=!1,ac=!1,O=!1,V=!1,Za=!1,Ua=!1,W=!1,Wa=!1,fc=!1,Xa=!1,Yb=!0,Ta=!0,ma=!1,Q={},Xb=L({},"annotation-xml audio colgroup desc foreignobject head iframe math mi mn mo ms mtext noembed noframes plaintext script style svg template thead title video xmp".split(" ")),Nd=L({},
["audio","video","img","source","image"]),Ra=null,ec=L({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),P=null,Md=y.createElement("form");m.isSupported&&(function(){try{g('<svg><p><textarea><img src="</textarea><img src=x abc=1//">').querySelector("svg img")&&(qb=!0)}catch(G){}}(),function(){try{var a=g("<x/><title>&lt;/title&gt;&lt;img&gt;");/<\/title/.test(a.querySelector("title").innerHTML)&&(rb=!0)}catch(H){}}());var Wd=function Wb(b){var e=void 0,
f=h(b);for(d("beforeSanitizeShadowDOM",b,null);e=f.nextNode();)d("uponSanitizeShadowNode",e,null),c(e)||(e.content instanceof sb&&Wb(e.content),a(e));d("afterSanitizeShadowDOM",b,null)};m.sanitize=function(b,d){var f=void 0,k=void 0,y=void 0,H=void 0;b||(b="\x3c!--\x3e");if("string"!==typeof b&&!e(b)){if("function"!==typeof b.toString)throw new TypeError("toString is not a function");b=b.toString();if("string"!==typeof b)throw new TypeError("dirty is not a string, aborting");}if(!m.isSupported){if("object"===
N(n.toStaticHTML)||"function"===typeof n.toStaticHTML){if("string"===typeof b)return n.toStaticHTML(b);if(e(b))return n.toStaticHTML(b.outerHTML)}return b}Za||p(d);m.removed=[];if(!ma)if(b instanceof ba)f=g("\x3c!--\x3e"),k=f.ownerDocument.importNode(b,!0),1===k.nodeType&&"BODY"===k.nodeName?f=k:"HTML"===k.nodeName?f=k:f.appendChild(k);else{if(!W&&!O&&!V&&Xa&&-1===b.indexOf("<"))return B?B.createHTML(b):b;f=g(b);if(!f)return W?null:bc}f&&Ua&&l(f.firstChild);for(var v=h(ma?b:f);d=v.nextNode();)3===
d.nodeType&&d===y||c(d)||(d.content instanceof sb&&Wd(d.content),a(d),y=d);y=null;if(ma)return b;if(W){if(Wa)for(H=Ud.call(f.ownerDocument);f.firstChild;)H.appendChild(f.firstChild);else H=f;fc&&(H=Vd.call(D,H,!0));return H}var t=V?f.outerHTML:f.innerHTML;O&&(t=t.replace(ad," "),t=t.replace(bd," "));return B&&Xa?B.createHTML(t):t};m.setConfig=function(a){p(a);Za=!0};m.clearConfig=function(){P=null;Za=!1};m.isValidAttribute=function(a,c,d){P||p({});a=a.toLowerCase();c=c.toLowerCase();return b(a,c,
d)};m.addHook=function(a,b){"function"===typeof b&&(C[a]=C[a]||[],C[a].push(b))};m.removeHook=function(a){C[a]&&C[a].pop()};m.removeHooks=function(a){C[a]&&(C[a]=[])};m.removeAllHooks=function(){C={}};return m}var md=ld();var nd={script:{attribute:"type",values:["application/json","application/ld+json"]}},od={USE_PROFILES:{html:!0,svg:!0,svgFilters:!0}};function S(a){var b=F({IN_PLACE:!0}),c=nc;this.B=a;this.$=1;this.j=md(self);this.P=md(self);a=Object.assign(b||{},Object.assign({},od,{ADD_ATTR:wc,ADD_TAGS:["use"],FORBID_TAGS:Object.keys(tc),FORCE_BODY:!0,RETURN_DOM:!0,ALLOW_UNKNOWN_PROTOCOLS:!0}));this.j.setConfig(a);pd(this,this.j,c);qd(this.P)}S.prototype.purifyHtml=function(a){return this.j.sanitize(a)};
S.prototype.purifyTagsForTripleMustache=function(a){a=this.P.sanitize(a,{ALLOWED_TAGS:vc,FORCE_BODY:!0,RETURN_DOM_FRAGMENT:!0});var b=this.B.createElement("div");b.appendChild(a);return b.innerHTML};S.prototype.getAllowedTags=function(){var a={};this.j.addHook("uponSanitizeElement",function(b,d){Object.assign(a,d.allowedTags)});var b=this.B.createElement("p");this.j.sanitize(b);Object.keys(tc).forEach(function(b){a[b]=!1});this.j.removeHook("uponSanitizeElement");return a};
S.prototype.validateAttributeChange=function(a,b,c){var d=a.nodeName.toLowerCase(),e=nd[d];if(e){var f=e,h=f.values;if(f.attribute===b&&(null==c||!h.includes(c)))return!1}if("a"===d&&"target"===b&&(null==c||!yc.includes(c)))return!1;if(null==c)return!0;if(rd(b)!==sd)return!1;var g=this.j.isValidAttribute(d,b,c);if(!g){var k=xc[d],l=k&&k.includes(b);if(!l&&!I(d,"amp-"))return!1}a=a.ownerDocument?a.ownerDocument:a;return c&&!Ic(d,b,c,a)?!1:!0};
function pd(a,b,c){function d(b){sc(b,function(){return String(a.$++)});m.forEach(function(a){delete p[a]});m.length=0;"use"===b.nodeName.toLowerCase()&&["href","xlink:href"].forEach(function(a){b.hasAttribute(a)&&!I(b.getAttribute(a),"#")&&(b.parentElement&&b.parentElement.removeChild(b),z().error("purifier",'Removed invalid <use>. use[href] must start with "#".'))})}function e(b,d){function e(){p[g]||(p[g]=!0,m.push(g))}var f=b.nodeName.toLowerCase(),g=d.attrName,h=d.attrValue;p=d.allowedAttributes;
if(I(f,"amp-"))e();else{if("a"==f&&"target"==g){var k=h.toLowerCase();h=yc.includes(k)?k:"_top"}var l=xc[f];l&&l.includes(g)&&e()}var n=rd(g);n===td&&(l=g.substring(1,g.length-1),b.setAttribute("data-amp-bind-"+l,h));n!==sd&&b.setAttribute("i-amphtml-binding","");Ic(f,g,h,a.B)?c&&h&&!I(g,"data-amp-bind-")&&(h=c(f,g,h)):(d.keepAttr=!1,z().error("purifier",'Removed invalid attribute %s[%s="%s"].',f,g,h));d.attrValue=h}function f(){l.forEach(function(a){delete k[a]});l.length=0}function h(a,b){var c=
b.tagName;k=b.allowedTags;I(c,"amp-")&&(k[c]=!g||uc[c]);"a"===c&&a.hasAttribute("href")&&!a.hasAttribute("target")&&a.setAttribute("target","_top");var d=nd[c];d&&(b=d.attribute,d=d.values,a.hasAttribute(b)&&d.includes(a.getAttribute(b))&&(k[c]=!0,l.push(c)))}var g=Kb(a.B),k,l=[],p,m=[];b.addHook("uponSanitizeElement",h);b.addHook("afterSanitizeElements",f);b.addHook("uponSanitizeAttribute",e);b.addHook("afterSanitizeAttributes",d)}
function qd(a){var b;a.addHook("uponSanitizeElement",function(a,d){var c=d.tagName;b=d.allowedTags;"template"===c&&(a=a.getAttribute("type"))&&"amp-mustache"===a.toLowerCase()&&(b.template=!0)});a.addHook("afterSanitizeElements",function(){b.template=!1})}var sd=0,td=1,ud=2;function rd(a){return"["==a[0]&&"]"==a[a.length-1]?td:I(a,"data-amp-bind-")?ud:sd};function vd(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,wd(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=Cb(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var h=c;return!!h[b]}
function wd(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){A().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var xd={},T=(xd["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},xd);function yd(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d;var f=d;if(vd(f,"ampdoc-fie")){f.__AMP_EXPERIMENT_BRANCHES=f.__AMP_EXPERIMENT_BRANCHES||{};for(var h in T)if(Hb.call(T,h)&&!Hb.call(f.__AMP_EXPERIMENT_BRANCHES,h))if(T[h].isTrafficEligible&&T[h].isTrafficEligible(f)){if(!f.__AMP_EXPERIMENT_BRANCHES[h]&&vd(f,h)){var g=T[h].branches;f.__AMP_EXPERIMENT_BRANCHES[h]=g[Math.floor(Math.random()*g.length)]||null}}else f.__AMP_EXPERIMENT_BRANCHES[h]=null;f="21065002"===
(f.__AMP_EXPERIMENT_BRANCHES?f.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:null)}else f=!1;var k=f;e&&!k?b=zd(c,b)?Ad(c,b):null:(a=Bd(a),a=Cd(a),b=zd(a,b)?Ad(a,b):null);return b}function U(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Ad(a,b)}function Dd(a,b){return Ed(Cd(a),b)}function Bd(a){return a.nodeType?U((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function Cd(a){a=Bd(a);return a.isSingleDoc()?a.win:a}
function Ad(a,b){zd(a,b);var c=Fd(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Gd(a,b){var c=Ed(a,b);if(c)return c;a=Fd(a);a[b]=Hd();return a[b].promise}function Ed(a,b){var c=Fd(a)[b];if(c){if(c.promise)return c.promise;Ad(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Fd(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function zd(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function Hd(){var a=new Jc,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function Id(a){return Jd(a,"amp-script","amp-script",void 0).then(function(a){return E(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","amp-script","amp-script","amp-script","amp-script")})}
function Jd(a,b,c,d){var e=Dd(a,b);if(e)return e;var f=Bd(a);return f.waitForBodyOpen().then(function(){return Kd(f.win,c,f.win.document.head)}).then(function(){if(d)var e=Dd(a,b);else e=f.win,e=e.__AMP_EXTENDED_ELEMENTS&&e.__AMP_EXTENDED_ELEMENTS[c]?Gd(Cd(a),b):null;return e})}function Ld(a){var b=yd(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=b.__AMP_TOP||(b.__AMP_TOP=b);return b!==c?Xd(b):Jd(a,"bind","amp-bind")}
function Kd(a,b,c){if(c){var d={};c=c.querySelectorAll("script[custom-element],script[custom-template]");for(var e=0;e<c.length;e++){var f=c[e];f=f.getAttribute("custom-element")||f.getAttribute("custom-template");d[f]=!0}d=Object.keys(d)}else d=[];if(!d.includes(b))return Promise.resolve();var h=U(a,"extensions");return h.waitForExtension(a,b)}
function Xd(a){return Mc(a.document).then(function(){return Kd(a,"amp-bind",a.document.head)}).then(function(){return a.__AMP_EXTENDED_ELEMENTS&&a.__AMP_EXTENDED_ELEMENTS["amp-bind"]?Gd(a,"bind"):null})};var Yd="change click dblclick input keypress submit".split(" ");function Zd(a){var b=this;this.S=a;this.O=this.X.bind(this);this.m=0;this.C=!1;Yd.forEach(function(a){b.S.addEventListener(a,b.O,!0)})}q=Zd.prototype;q.dispose=function(){var a=this;Yd.forEach(function(b){a.S.removeEventListener(b,a.O,!0)})};q.hasBeenActive=function(){return 0<this.m};q.isActive=function(){return 0<this.m&&5E3>=Date.now()-this.m||this.C};q.getLastActivationTime=function(){return this.m};
q.expandLongTask=function(a){var b=this;this.isActive()&&(this.C=!0,a.catch(function(){}).then(function(){b.C=!1;b.m=Date.now()}))};q.isInLongTask=function(){return this.C};q.X=function(a){a.isTrusted&&(this.m=Date.now())};function $d(a,b){var c="0.1",d=Eb().esm?".mjs":".js";b?(b=a.protocol+"//"+a.host,"about:"==a.protocol&&(b=""),a=b+"/dist"):a=Fb.cdn;var e=Eb().rtvVersion;null==c&&(c="0.1");var f=c?"-"+c:"";return a+"/rtv/"+e+"/v0/amp-script-worker"+f+d};self.__AMP_ERRORS=self.__AMP_ERRORS||[];function ae(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function be(a){if("undefined"!==typeof TextEncoder)a=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}a=b}return a};function X(a){a=AMP.BaseElement.call(this,a)||this;a.T=U(a.win,"vsync");a.V=null;a.F=null;a.D=null;a.o="amp-script[unknown].js";a.R=!1;a.w=!1;return a}var Y=AMP.BaseElement;X.prototype=qa(Y.prototype);X.prototype.constructor=X;if(va)va(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var ce=Object.getOwnPropertyDescriptor(Y,Z);ce&&Object.defineProperty(X,Z,ce)}else X[Z]=Y[Z];X.ca=Y.prototype;q=X.prototype;q.isLayoutSupported=function(a){return"container"==a||Jb(a)};
q.buildCallback=function(){var a=this;(this.w=this.element.hasAttribute("data-ampdevmode")||this.element.ownerDocument.documentElement.hasAttribute("data-ampdevmode"))&&z().warn("amp-script","JavaScript size and script hash requirements are disabled in development mode.",this.element);return Id(this.element).then(function(b){a.setService(b)})};
q.onMeasureChanged=function(){if(!this.R){var a=this.getLayoutBox(),b=a.height;0===a.width&&0===b&&z().warn("amp-script","Skipped initializing amp-script due to zero width and height.",this.element)}};q.setService=function(a){this.D=a};q.getUserActivation=function(){return this.F};
q.layoutCallback=function(){var a=this;this.R=!0;if(this.element.sizerElement){var b=this.win.document.createElement("div");this.applyFillContent(b,!0);for(var c=this.getRealChildren(),d=0;d<c.length;d++)b.appendChild(c[d]);this.element.appendChild(b)}this.F=new Zd(this.element);this.o=this.element.hasAttribute("src")?'amp-script[src="'+this.element.getAttribute("src")+'"].js':'amp-script[script="'+this.element.getAttribute("script")+'"].js';var e=de(this,this.o);if(!e)return z().error("amp-script",
'"src" or "script" attribute is required.'),Promise.reject(Error("CANCELLED"));var f=Promise.all([ee(this),e]).then(function(b){var c=b[0],d=b[1];return!a.w&&a.D.sizeLimitExceeded(d.length)?(z().error("amp-script","Maximum total script size exceeded (%s). %s is disabled. See https://amp.dev/documentation/components/amp-script/#size-of-javascript-code.",15E4,a.o),a.element.classList.add("i-amphtml-broken"),[]):[c,d]}),h=this.element.getAttribute("sandbox")||"",g=h.split(" ").map(function(a){return a.trim()});
d={authorURL:this.o,mutationPump:this.aa.bind(this),longTask:function(b){a.F.expandLongTask(b)},sanitizer:new fe(this,g),onCreateWorker:function(a){A().info("amp-script","Create worker:",a)},onSendMessage:function(a){A().info("amp-script","To worker:",a)},onReceiveMessage:function(a){A().info("amp-script","From worker:",a)}};zb(b||this.element,f,d).then(function(b){a.V=b});return f};
function ee(a){var b=!1,c=$d(a.win.location,b);return U(a.win,"xhr").fetchText(c,{ampCors:!1}).then(function(a){return a.text()})}
function de(a,b){var c=a.element.getAttribute("src");if(c)return ge(a,c,b);var d=a.element.getAttribute("script");if(d){var e=a.getAmpDoc().getElementById(d);E(e,"[%s] %s could not find element with #%s.","amp-script",b,d);var f=e.getAttribute("target");E("amp-script"===f,'[%s] script#%s must have target="amp-script".',"amp-script",d);var h=e.textContent;return a.w?Promise.resolve(h):a.D.checkSha384(h,b).then(function(){return h})}return null}
function ge(a,b,c){return U(a.win,"xhr").fetchText(b,{ampCors:!1}).then(function(b){if(b.url&&he(a,b.url)){var d=b.headers.get("Content-Type");if(!d||!I(d,"application/javascript")&&!I(d,"text/javascript"))throw z().error("amp-script",'Same-origin "src" requires "Content-Type: text/javascript" or "Content-Type: application/javascript". Fetched source for %s has "Content-Type: %s". See https://amp.dev/documentation/components/amp-script/#security-features.',c,d),Error();return b.text()}return a.w?
b.text():b.text().then(function(b){return a.D.checkSha384(b,c).then(function(){return b})})})}function he(a,b){var c=yd(a.element,"url"),d=c.getSourceOrigin(a.getAmpDoc().getUrl()),e=c.parse(b).origin;return d===e}q.isMutationAllowedByFixedSize=function(){return Jb(this.getLayout())};q.isMutationAllowedByUserGesture=function(){return this.F.isActive()};
q.aa=function(a,b){var c=this;1==b&&this.T.mutate(function(){return c.element.classList.add("i-amphtml-hydrated")});var d=this.isMutationAllowedByFixedSize()||this.isMutationAllowedByUserGesture();this.T.mutate(function(){var b=a(d),c=Ib();b.forEach(function(a){c[a]=c[a]+1||1});Object.keys(c).forEach(function(a){var b=c[a];z().error("amp-script",'Dropped %sx "%s" mutation(s); user gesture is required with [layout=container].',b,ie(a))})});d||2!=b||(this.V.terminate(),this.element.classList.remove("i-amphtml-hydrated"),
this.element.classList.add("i-amphtml-broken"),z().error("amp-script","%s was terminated due to illegal mutation.",this.o))};function ie(a){switch(a){case "0":return"ATTRIBUTES";case "1":return"CHARACTER_DATA";case "2":return"CHILD_LIST";case "3":return"PROPERTIES";default:return"OTHER"}}function je(a){this.I=0;this.h=[];var b=a.getMetaByName("amp-script-src");b&&(this.h=b.split(" ").map(function(a){return a.trim()}).filter(function(a){return a.length}));this.Z=U(a.win,"crypto")}
je.prototype.checkSha384=function(a,b){var c=this;a=be(a);return this.Z.sha384Base64(a).then(function(a){if(!a||!c.h.includes("sha384-"+a))throw z().error("amp-script",'Script hash not found. %s must have "sha384-%s" in meta[name="amp-script-src"]. See https://amp.dev/documentation/components/amp-script/#security-features.',b,a),Error();})};je.prototype.sizeLimitExceeded=function(a){this.I+=a;return 15E4<this.I};var ke="form button fieldset input object output select textarea".split(" ");
function fe(a,b){var c=this;this.G=a.win;this.J=a.element;this.K=new S(a.win.document);this.l=this.K.getAllowedTags();this.N=function(){return a.isMutationAllowedByUserGesture()};this.ba=function(){return!c.N()&&a.isMutationAllowedByFixedSize()};this.l["amp-img"]=!0;this.l["amp-layout"]=!0;this.l["amp-pixel"]=!1;this.M=b.includes("allow-forms");ke.forEach(function(a){c.l[a]=c.M})}q=fe.prototype;
q.sanitize=function(a){var b=a.nodeName.toLowerCase(),c=this.l[b];c||le(this,b)||z().warn("amp-script","Sanitized node:",a);return c};
q.setAttribute=function(a,b,c){var d=a.nodeName.toLowerCase();if(this.l[d]){var e=b.toLowerCase();if(this.K.validateAttributeChange(a,e,c))return null==c?a.removeAttribute(e):(b=nc(d,e,c),a.setAttribute(e,b)),"a"===d&&a.hasAttribute("href")&&!a.hasAttribute("target")&&a.setAttribute("target","_top"),!0}le(this,d)||z().warn("amp-script",'Sanitized [%s]="%s":',b,c,a);return!1};
function le(a,b){return!a.M&&ke.includes(b)?(z().warn("amp-script",'Form elements (%s) are not allowed without sandbox="allow-forms".',b),!0):!1}q.setProperty=function(a,b,c){var d=b.toLowerCase();return this.K.validateAttributeChange(a,d,c)?(a[b]=c,!0):!1};q.getStorage=function(a,b){if(2===a)return Ld(this.J).then(function(a){if(a)return a.getStateValue(b||".")});a=0===a?this.G.localStorage:1===a?this.G.sessionStorage:null;for(var c={},d=0;d<a.length;d++){var e=a.key(d);e&&!I(e,"amp-")&&(c[e]=a.getItem(e))}return c};
q.setStorage=function(a,b,c){var d=this;if(2===a)return Ld(this.J).then(function(a){if(a){var b=ae(c,function(){A().error("amp-script","Invalid AMP.setState() argument: %s",c)});if(b){var e=d.N(),g=d.ba()?[d.J]:void 0;e||g||z().warn("amp-script","AMP.setState only updated page state and did not reevaluate bindings due to lack of recent user interaction.");a.setState(b,{skipEval:!e&&!g,skipAmpState:!1,constrain:g})}}});a=0===a?this.G.localStorage:1===a?this.G.sessionStorage:null;null===b?null===c&&
z().error("amp-script","Storage.clear() is not supported in amp-script."):I(b,"amp-")?z().error("amp-script",'Invalid "amp-" prefix for storage key: %s',b):null===c?a.removeItem(b):a.setItem(b,c);return Promise.resolve()};(function(a){a.registerServiceForDoc("amp-script",je);a.registerElement("amp-script",X,"amp-script{opacity:0.7}amp-script.i-amphtml-hydrated{opacity:1}\n/*# sourceURL=/extensions/amp-script/0.1/amp-script.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-script-0.1.js.map
